"""Shared state bridge to dashboard/main.py, and the module-level singletons
other dashboard_workflows modules decorate their entry points with.
"""

from __future__ import annotations

from functools import wraps
from typing import Any, Callable

_MAIN_GLOBAL_NAMES = (
    "Any",
    "Callable",
    "Path",
    "json",
    "os",
    "re",
    "subprocess",
    "sys",
    "threading",
    "time",
    "datetime",
    "timezone",
    "html_escape",
    "quote",
    "quote_plus",
    "DASHBOARD_GUARDRAILS",
    "QUALITY_HERO_CONFLUENCE_ANCHOR",
    "DELIVERY_CHECKLIST_CONFLUENCE_ANCHOR",
    "BMW_PIPELINE_PYTHON_CONFLUENCE_ANCHOR",
    "SG_DAILY_CONFLUENCE_ANCHOR",
    "MANUAL_REVIEW_STATUSES",
    "MANUAL_REVIEW_RECORD_VERDICTS",
    "MANUAL_REVIEW_EMPTY_NOTE",
    "_MANUAL_REVIEW_PENDING_VERDICT",
    "_TICKET_ID_PATTERN",
    "SETUP_COMPLETE_NOTE",
    "SCREENSHOT_TEST_STATE_OWNERSHIP_NOTE",
    "DAILY_DIGEST_BUILD_PACKAGE_ACTION_ID",
    "DAILY_DIGEST_BUILD_PACKAGE_ACTION_LABEL",
    "QUALITY_HERO_REPORT_ACTION_ID",
    "QUALITY_HERO_REPORT_ACTION_LABEL",
    "DAILY_DIGEST_TICKET_ID_PLACEHOLDER",
    "_DAILY_DIGEST_PARTIAL_SECTION_KEYS",
    "_BUILD_PACKAGE_TIMEOUT_SECONDS",
    "_BUILD_PACKAGE_STDOUT_TAIL_LINES",
    "_BUILD_PACKAGE_STDOUT_TAIL_BYTES",
    "_BUILD_PACKAGE_FILE_ACTIVITY_LIMIT",
    "_BUILD_PACKAGE_TYPICAL_RANGE_LABEL",
    "_QUALITY_HERO_REPORT_TIMEOUT_SECONDS",
    "_BATCH_FULL_QA_TIMEOUT_SECONDS",
    "_BATCH_FULL_QA_TYPICAL_RANGE_LABEL",
    "LONG_RUNNING_NOTIFICATION_SECONDS",
    "VERBOSE_TOOLTIP_ENV",
    "_workspace",
    "_utc_now",
    "_operator_state_path",
    "_read_operator_state_json",
    "_write_active_ticket_state",
    "_dashboard_active_ticket_id",
    "_daily_digest_ticket_context",
    "_dashboard_notifications_enabled",
    "_write_dashboard_notifications_preference",
    "_full_qa_wizard_state_path",
    "_read_full_qa_wizard_state",
    "_write_full_qa_wizard_state",
    "_delete_full_qa_wizard_state",
    "_payload_items",
    "_sanitized_payload",
    "_payload_summary",
    "_dashboard_changed_profiles",
    "_dashboard_data_uri",
    "_pipeline_traceback",
    "_screenshot_review_visual_rows",
    "_file_activity_visual_items",
    "_render_status_chip",
    "_render_page_panel",
    "_render_confluence_anchor",
    "_render_page_confluence_anchors",
    "_render_empty_state_note",
    "_render_action_visuals",
    "_render_action_technical_details",
    "_attach_tooltip",
    "_copy_dashboard_text_to_clipboard",
    "_copy_dashboard_link_to_clipboard",
    "_start_background_poll_timer",
    "_start_io_bound_poll_timer",
    "_cancel_background_poll_timer",
    "_parent_slot_deleted",
    "_ignorable_nicegui_runtime_error",
    "_run_javascript_if_client_alive",
    "operator_ui_root",
    "sgfx_cli_command",
    "hidden_subprocess_kwargs",
    "ensure_parent",
    "append_activity_entry",
    "notify_desktop_completion",
    "record_full_qa_run_history",
    "build_qa_pass_report_summary",
    "default_qa_pass_report_zip_path",
    "export_qa_pass_report_zip",
    "write_qa_pass_report_html",
    "build_full_qa_pass",
    "get_run_profile",
    "build_latest_daily_digest",
    "render_daily_digest_text",
    "build_screenshot_review_viewer",
    "compute_diff_delta_badge",
    "compute_diff_regression_badge",
    "run_missing_actual_diagnostic_chain",
    "render_missing_actual_diagnostic_text",
    "MISSING_ACTUAL_DIAGNOSTIC_ACTION_ID",
    "build_visual_review_prep",
    "read_bmw_screenshot_state",
    "check_screenshot_capture_environment",
    "check_screenshot_export_artifact",
    "record_operator_handoff",
    "start_delivery_workbook_generation",
    "poll_delivery_workbook_generation",
    "cancel_delivery_workbook_generation",
    "build_delivery_workbook_trigger",
    "GENERATE_WORKBOOK_ACTION_ID",
    "GENERATE_WORKBOOK_ACTION_LABEL",
    "GENERATE_WORKBOOK_TIMEOUT_SECONDS",
    "start_screenshot_capture",
    "poll_screenshot_capture",
    "cancel_screenshot_capture",
    "start_screenshot_capture_with_export_check",
    "poll_screenshot_capture_with_export_check",
    "cancel_screenshot_capture_with_export_check",
    "SCREENSHOT_CAPTURE_ACTION_ID",
    "SCREENSHOT_CAPTURE_ACTION_LABEL",
    "SCREENSHOT_CAPTURE_TIMEOUT_SECONDS",
    "start_dependency_setup_action",
    "poll_dependency_setup_action",
    "cancel_dependency_setup_action",
    "build_dependency_onboarding_status",
    "QUALITY_HERO_STEPS",
    "review_template_for_profile",
    "list_car_review_templates",
    "load_manual_review_session",
    "create_manual_review_session_from_template",
    "record_manual_review_step",
    "record_manual_review_dashboard_step",
    "build_manual_review_assist",
    "build_manual_review_assist_from_auto_checks",
    "apply_manual_review_suggestions",
    "run_manual_review_auto_checks",
    "_full_qa_pass_page",
    "_batch_full_qa_pass_page",
    "_is_truthy_trigger",
    "_full_qa_pass_token",
    "_full_qa_pass_dedup_key",
    "_should_fire_full_qa_pass",
    "_reset_full_qa_pass_dedup",
    "_publish_live_state",
    "_snapshot_with_full_qa_payload",
    "_screenshot_review_viewer_output_root",
    "_missing_actual_diagnostics_output_root",
    "_qa_pass_report_output_root",
    "_qa_pass_report_url",
    "build_dashboard_qa_pass_report",
    "export_dashboard_qa_pass_report",
    "_screenshot_review_viewer_url",
    "_materialize_screenshot_review_viewer_for_dashboard",
    "_notify_completion_safe",
    "_full_qa_completion_notification",
    "_manual_review_profile_token",
    "_manual_review_dashboard_session_id",
    "_load_manual_review_dashboard_session",
    "_ensure_manual_review_dashboard_session",
    "_manual_review_step_recorded",
    "_manual_review_step_detail",
    "_manual_review_page",
    "_dashboard_review_package_command",
    "_dashboard_full_qa_pass_command",
    "_batch_profile_safe_name",
    "_read_json_payload",
    "_batch_step_payload",
    "_batch_profile_result",
    "_batch_progress_payload",
    "_complete_batch_full_qa_pass",
    "_start_batch_profile_process",
    "start_dashboard_batch_full_qa_pass",
    "request_cancel_dashboard_batch_full_qa_pass",
    "poll_dashboard_batch_full_qa_pass",
    "_review_build_progress_payload",
    "_complete_review_package_build",
    "start_dashboard_review_package_build",
    "poll_dashboard_review_package_build",
    "cancel_dashboard_review_package_build",
    "build_dashboard_review_package",
    "_quality_hero_report_output_root",
    "_dashboard_quality_hero_report_command",
    "build_dashboard_quality_hero_report",
    "_build_action_visual_payload",
    "_full_qa_int",
    "_full_qa_step_payload",
    "_full_qa_step_map",
    "_full_qa_step_status",
    "_full_qa_screenshot_counts",
    "_full_qa_risk_draft",
    "_full_qa_manual_review_draft",
    "_full_qa_handoff_draft",
    "_full_qa_bulk_ack_drafts",
    "_render_daily_digest_panel",
    "_render_operator_handoff_panel",
    "_render_manual_review_panel",
    "_render_batch_full_qa_pass_panel",
    "_render_full_qa_pass_panel",
)


def _sync_main_globals(target_globals: dict[str, Any] | None = None) -> None:
    from sg_preflight.dashboard import main as dashboard_main

    if target_globals is None:
        target_globals = globals()
    for name in _MAIN_GLOBAL_NAMES:
        if hasattr(dashboard_main, name):
            target_globals[name] = getattr(dashboard_main, name)


def _with_main_globals(func: Callable[..., Any]) -> Callable[..., Any]:
    @wraps(func)
    def wrapper(*args: Any, **kwargs: Any) -> Any:
        _sync_main_globals(func.__globals__)
        return func(*args, **kwargs)

    return wrapper
