"""Stateful, operator-triggered dashboard workflows and their panel renderers.

Companion to dashboard_pages_config.py (which owns the read-only report
pages); this module owns the pages that launch a background action, track its
progress, and require a manual review verdict:

- Full QA Pass and Batch Full QA Pass: page payloads, the reconnect-storm
  trigger dedup, step/draft helpers, and panel rendering.
- The manual review wizard: session state and page rendering.
- Review-package build, Quality-Hero report generation, and the QA pass
  report / screenshot review viewer output paths.
- Live-state snapshot publishing and desktop completion notifications shared
  across the workflows above.

The implementation lives in the `dashboard_workflows` package, split by the
section boundaries above (state_bridge, qa_pass_payloads, live_state_pub,
report_paths, notifications, manual_review_wizard, jobs, renderers). This
module is the explicit-import facade over that package: every name this
module used to define at top level is re-exported here unchanged so existing
`from sg_preflight.dashboard_pages_workflows import ...` call sites keep
working.

Most functions in the package run against globals defined in
dashboard/main.py (`_sync_main_globals` / `_with_main_globals` bridge that
namespace in) rather than importing them directly, so the package can be
developed and tested without a circular import on dashboard/main.py.
"""

from __future__ import annotations

from sg_preflight.dashboard_workflows.state_bridge import (
    _MAIN_GLOBAL_NAMES,
    _sync_main_globals,
    _with_main_globals,
)
from sg_preflight.dashboard_workflows.qa_pass_payloads import (
    FULL_QA_PASS_DEDUP_BUCKET_SECONDS,
    FULL_QA_PASS_DEDUP_WINDOW_SECONDS,
    _TRUTHY_TRIGGERS,
    _batch_full_qa_pass_page,
    _full_qa_pass_dedup_key,
    _full_qa_pass_dedup_lock,
    _full_qa_pass_dedup_tokens,
    _full_qa_pass_page,
    _full_qa_pass_token,
    _is_truthy_trigger,
    _reset_full_qa_pass_dedup,
    _should_fire_full_qa_pass,
)
from sg_preflight.dashboard_workflows.live_state_pub import (
    _publish_live_state,
    _snapshot_with_full_qa_payload,
)
from sg_preflight.dashboard_workflows.report_paths import (
    _materialize_screenshot_review_viewer_for_dashboard,
    _missing_actual_diagnostics_output_root,
    _qa_pass_report_output_root,
    _qa_pass_report_url,
    _screenshot_review_viewer_output_root,
    _screenshot_review_viewer_url,
    build_dashboard_qa_pass_report,
    export_dashboard_qa_pass_report,
)
from sg_preflight.dashboard_workflows.notifications import (
    _full_qa_completion_notification,
    _notify_completion_safe,
)
from sg_preflight.dashboard_workflows.manual_review_wizard import (
    _ensure_manual_review_dashboard_session,
    _load_manual_review_dashboard_session,
    _manual_review_dashboard_session_id,
    _manual_review_page,
    _manual_review_profile_token,
    _manual_review_step_detail,
    _manual_review_step_recorded,
)
from sg_preflight.dashboard_workflows.jobs import (
    _BATCH_FULL_QA_TIMEOUT_SECONDS,
    _BATCH_FULL_QA_TYPICAL_RANGE_LABEL,
    _BUILD_PACKAGE_FILE_ACTIVITY_LIMIT,
    _BUILD_PACKAGE_STDOUT_TAIL_BYTES,
    _BUILD_PACKAGE_STDOUT_TAIL_LINES,
    _BUILD_PACKAGE_TIMEOUT_SECONDS,
    _BUILD_PACKAGE_TYPICAL_RANGE_LABEL,
    _QUALITY_HERO_REPORT_TIMEOUT_SECONDS,
    BatchFullQaPassJob,
    ReviewPackageBuildJob,
    _batch_profile_result,
    _batch_profile_safe_name,
    _batch_progress_payload,
    _batch_step_payload,
    _build_combined_tail_lines,
    _build_package_file_activity,
    _build_tail_lines,
    _build_tail_text,
    _complete_batch_full_qa_pass,
    _complete_review_package_build,
    _dashboard_full_qa_pass_command,
    _dashboard_quality_hero_report_command,
    _dashboard_review_package_command,
    _elapsed_label,
    _quality_hero_report_output_root,
    _read_json_payload,
    _review_build_progress_payload,
    _start_batch_profile_process,
    _size_label,
    _validate_review_package_inputs,
    build_dashboard_quality_hero_report,
    build_dashboard_review_package,
    cancel_dashboard_review_package_build,
    poll_dashboard_batch_full_qa_pass,
    poll_dashboard_review_package_build,
    request_cancel_dashboard_batch_full_qa_pass,
    start_dashboard_batch_full_qa_pass,
    start_dashboard_review_package_build,
)
from sg_preflight.dashboard_workflows.renderers import (
    DAILY_DIGEST_BUILD_PACKAGE_ACTION_ID,
    DAILY_DIGEST_BUILD_PACKAGE_ACTION_LABEL,
    DAILY_DIGEST_TICKET_ID_PLACEHOLDER,
    MISSING_ACTUAL_CHAIN_UNAVAILABLE_SUMMARY,
    QUALITY_HERO_REPORT_ACTION_ID,
    QUALITY_HERO_REPORT_ACTION_LABEL,
    _DAILY_DIGEST_PARTIAL_SECTION_KEYS,
    _FULL_QA_DRAFT_STEP_IDS,
    _build_action_visual_payload,
    _empty_action_visual_payload,
    _full_qa_bulk_ack_drafts,
    _full_qa_handoff_draft,
    _full_qa_int,
    _full_qa_manual_review_draft,
    _full_qa_risk_draft,
    _full_qa_screenshot_counts,
    _full_qa_step_map,
    _full_qa_step_payload,
    _full_qa_step_status,
    _genericize_failed_summary,
    _render_action_technical_details,
    _render_action_visuals,
    _render_batch_full_qa_pass_panel,
    _render_daily_digest_panel,
    _render_full_qa_pass_panel,
    _render_manual_review_panel,
    _render_operator_handoff_panel,
)

__all__ = [
    "_MAIN_GLOBAL_NAMES",
    "_sync_main_globals",
    "_with_main_globals",
    "_full_qa_pass_page",
    "_batch_full_qa_pass_page",
    "_TRUTHY_TRIGGERS",
    "_is_truthy_trigger",
    "FULL_QA_PASS_DEDUP_WINDOW_SECONDS",
    "_full_qa_pass_dedup_lock",
    "_full_qa_pass_dedup_tokens",
    "FULL_QA_PASS_DEDUP_BUCKET_SECONDS",
    "_full_qa_pass_token",
    "_full_qa_pass_dedup_key",
    "_should_fire_full_qa_pass",
    "_reset_full_qa_pass_dedup",
    "_publish_live_state",
    "_snapshot_with_full_qa_payload",
    "_screenshot_review_viewer_output_root",
    "_missing_actual_diagnostics_output_root",
    "_screenshot_review_viewer_url",
    "_qa_pass_report_output_root",
    "_qa_pass_report_url",
    "build_dashboard_qa_pass_report",
    "export_dashboard_qa_pass_report",
    "_materialize_screenshot_review_viewer_for_dashboard",
    "_notify_completion_safe",
    "_full_qa_completion_notification",
    "DAILY_DIGEST_BUILD_PACKAGE_ACTION_ID",
    "DAILY_DIGEST_BUILD_PACKAGE_ACTION_LABEL",
    "QUALITY_HERO_REPORT_ACTION_ID",
    "QUALITY_HERO_REPORT_ACTION_LABEL",
    "DAILY_DIGEST_TICKET_ID_PLACEHOLDER",
    "_DAILY_DIGEST_PARTIAL_SECTION_KEYS",
    "_manual_review_profile_token",
    "_manual_review_dashboard_session_id",
    "_load_manual_review_dashboard_session",
    "_ensure_manual_review_dashboard_session",
    "_manual_review_step_recorded",
    "_manual_review_step_detail",
    "_manual_review_page",
    "_BUILD_PACKAGE_TIMEOUT_SECONDS",
    "_BUILD_PACKAGE_STDOUT_TAIL_LINES",
    "_BUILD_PACKAGE_STDOUT_TAIL_BYTES",
    "_BUILD_PACKAGE_FILE_ACTIVITY_LIMIT",
    "_BUILD_PACKAGE_TYPICAL_RANGE_LABEL",
    "_QUALITY_HERO_REPORT_TIMEOUT_SECONDS",
    "_BATCH_FULL_QA_TIMEOUT_SECONDS",
    "_BATCH_FULL_QA_TYPICAL_RANGE_LABEL",
    "ReviewPackageBuildJob",
    "BatchFullQaPassJob",
    "_validate_review_package_inputs",
    "_dashboard_review_package_command",
    "_build_tail_text",
    "_build_tail_lines",
    "_build_combined_tail_lines",
    "_size_label",
    "_build_package_file_activity",
    "_elapsed_label",
    "_dashboard_full_qa_pass_command",
    "_batch_profile_safe_name",
    "_read_json_payload",
    "_batch_step_payload",
    "_batch_profile_result",
    "_batch_progress_payload",
    "_complete_batch_full_qa_pass",
    "_start_batch_profile_process",
    "start_dashboard_batch_full_qa_pass",
    "request_cancel_dashboard_batch_full_qa_pass",
    "poll_dashboard_batch_full_qa_pass",
    "_review_build_progress_payload",
    "_complete_review_package_build",
    "start_dashboard_review_package_build",
    "poll_dashboard_review_package_build",
    "cancel_dashboard_review_package_build",
    "build_dashboard_review_package",
    "_quality_hero_report_output_root",
    "_dashboard_quality_hero_report_command",
    "build_dashboard_quality_hero_report",
    "MISSING_ACTUAL_CHAIN_UNAVAILABLE_SUMMARY",
    "_build_action_visual_payload",
    "_empty_action_visual_payload",
    "_render_action_visuals",
    "_render_action_technical_details",
    "_FULL_QA_DRAFT_STEP_IDS",
    "_full_qa_int",
    "_full_qa_step_payload",
    "_full_qa_step_map",
    "_full_qa_step_status",
    "_full_qa_screenshot_counts",
    "_full_qa_risk_draft",
    "_full_qa_manual_review_draft",
    "_full_qa_handoff_draft",
    "_full_qa_bulk_ack_drafts",
    "_render_daily_digest_panel",
    "_render_operator_handoff_panel",
    "_render_manual_review_panel",
    "_genericize_failed_summary",
    "_render_batch_full_qa_pass_panel",
    "_render_full_qa_pass_panel",
]
